modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors = "QiuYe"
description = "${mod_description}"
displayURL = "${mod_url}"
credits = ""

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = false
versionRange = "[7,)"
ordering = "BEFORE"
side = "BOTH"
